### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given

### ISSUE THREAD

**Issue by socialcyberdog** [bamarni/symfony-console-autocomplete#54]
This tool does not work oob, error:

```
user@bionic:~/tmp/symfony$ symfony-autocomplete composer
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/user/.config/composer/vendor/bamarni/symfony-console-autocomplete/src/DumpCommand.php on line 76 and defined in /home/user/.config/composer/vendor/symfony/process/Process.php:140
Stack trace:
#0 /home/user/.config/composer/vendor/bamarni/symfony-console-autocomplete/src/DumpCommand.php(76): Symfony\Component\Process\Process->__construct('composer  list ...')
#1 /home/user/.config/composer/vendor/symfony/console/Command/Command.php(255): Bamarni\Symfony\Console\Autocomplete\DumpCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/user/.config/composer/vendor/symfony/console/Application.php(925): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/user/.config/composer/vendor/symfony/c in /home/user/.config/composer/vendor/symfony/process/Process.php on line 140

user@bionic:~/tmp/symfony$ php --version
PHP 7.3.15-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.15, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.15-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by brainexe** [comment]
see this PR: #53 I'm also waiting for the merge

**Comment by rquadling** [comment]
Apologies for the delay, v1.3.6 has been released which should address this issue.

Thank you for your patience.
